openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /sample:
    post:
      summary: Create a new sample
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    get:
      summary: Get all samples
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
components: {}
servers:
  - url: http://localhost:3000